// This file is auto-generated by AssetsPostprocessor.
// Do not modify this file manually.
//
// To regenerate this file manually, select the menu item Tools > LunarFramework > Generate R.cs.
//

using Luna;
using UnityEngine;

namespace R
{
    public static class Audios
    {
        public static Asset<AudioClip> SfxBack => new("Assets/Game/Common/Audios/sfx_back.mp3");
        public static Asset<AudioClip> SfxConfirm => new("Assets/Game/Common/Audios/sfx_confirm.mp3");
        public static Asset<AudioClip> SfxSelect => new("Assets/Game/Common/Audios/sfx_select.mp3");
        public static Asset<AudioClip> タンホイザーとアイーダメドレー => new("Assets/Game/Common/Commend/Audios/タンホイザーとアイーダメドレー.mp3");
        public static Asset<AudioClip> ハレルヤ => new("Assets/Game/Common/Commend/Audios/ハレルヤ.mp3");
        public static Asset<AudioClip> 威風堂々 => new("Assets/Game/Common/Commend/Audios/威風堂々.mp3");
        public static Asset<AudioClip> 拍手 => new("Assets/Game/Common/Commend/Audios/拍手.mp3");
        public static Asset<AudioClip> 指笛 => new("Assets/Game/Common/Commend/Audios/指笛.mp3");
        public static Asset<AudioClip> 歓声 => new("Assets/Game/Common/Commend/Audios/歓声.mp3");
        public static Asset<AudioClip> 見よ勇者は帰る => new("Assets/Game/Common/Commend/Audios/見よ、勇者は帰る.mp3");
        public static Asset<AudioClip> BgmRouletteLoop => new("Assets/Game/Roulette/Audios/bgm_roulette_loop.mp3");
        public static Asset<AudioClip> SfxRouletteGameDecelerating => new("Assets/Game/Roulette/Audios/sfx_roulette_game_decelerating.mp3");
        public static Asset<AudioClip> SfxRouletteGameRotating => new("Assets/Game/Roulette/Audios/sfx_roulette_game_rotating.mp3");
        public static Asset<AudioClip> BgmYamanote => new("Assets/Game/Yamanote/Audios/bgm_yamanote.mp3");

    }
}